import './components/profile/drag-drop-file.js'
import './components/profile/profile-tabs.js'
import './components/profile/profile-menu.js'
import './components/profile/close-tg-banner.js'
import './components/profile/business-card.js'
import './components/profile/copy-link.js'
import './components/profile/add-question.js'